version: "2"
linters:
  enable:
    - ginkgolinter
    - importas
    - misspell
    - revive
  settings:
    revive:
      severity: error
      rules:
        - name: exported
        - name: if-return
          disabled: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
    rules:
    - linters:
      - staticcheck
      text: 'SA1019:' # Excludes messages where deprecated variables are used
severity:
  default: error
formatters:
  enable:
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
